# Generated by Django 5.1.7 on 2025-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='venues',
            field=models.TextField(blank=True, help_text='Enter venue names separated by commas (e.g., Mumbai, Chennai, Mohali)', null=True),
        ),
    ]
