# Generated by Django 5.1.7 on 2025-03-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_player_team'),
        ('tournaments', '0005_alter_tournament_gap_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mom_awards', to='teams.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='teams.team'),
        ),
    ]
