# Generated by Django 5.1.7 on 2025-04-04 17:11

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_mom_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_winner',
            field=models.TextField(blank=True, null=True, verbose_name=teams.models.Team),
        ),
    ]
