# Generated by Django 5.1.7 on 2025-04-04 17:27

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_winner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=teams.models.Team),
        ),
    ]
