# Generated by Django 5.1.7 on 2025-03-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_initial'),
        ('teams', '0003_alter_player_team'),
        ('tournaments', '0005_alter_tournament_gap_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('extras', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='tournaments.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='BowlingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.FloatField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('wides', models.IntegerField(default=0)),
                ('noballs', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('inning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_scores', to='scores.inning')),
            ],
        ),
        migrations.CreateModel(
            name='BattingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('out_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bowled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wickets_taken', to='teams.player')),
                ('caught_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='teams.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('inning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_scores', to='scores.inning')),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
